### ISSUE TITLE
Notice problem

### ISSUE THREAD

**Issue by magnolia61** [JohnFF/Email-Amender#3]
I do not know how severe this problem is, but I thought you'd like to hear about it.
When registering for an event, I see the following in the drupal recent error log as a warning.
Is this an easy fix?

Warning: array_key_exists() expects parameter 2 to be array, null given in emailamender_performreplacement() (line 161 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/Email-Amender/emailamender.php).

**Comment by JohnFF** [comment]
Dear Richard,

Thank you for taking the time to report this bug to me. I'm sorry that
you've encountered a problem with the extension.

Please could you tell me:

1) Which version of CiviCRM you are on?
2) Which CMS (and which version) you are on as well?

Thank you, I hope to be able to report back to you soon,

John

On Tue, Jan 20, 2015 at 12:04 AM, Richard van Oosterhout <
notifications@github.com> wrote:

> I do not know how severe this problem is, but I thought you'd like to hear
> about it.
> When registering for an event, I see the following in the drupal recent
> error log as a warning.
> Is this an easy fix?
>
> Warning: array_key_exists() expects parameter 2 to be array, null given in
> emailamender_performreplacement() (line 161 of /home/ozk/domains/
> ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/Email-Amender/emailamender.php
> ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnFF/Email-Amender/issues/3>.
>



-- 
John Prescott
Lead Developer
Future First
john@futurefirst.org.uk

**Comment by magnolia61** [comment]
civicrm 4.5.5 / Drupal 7.34
Iḿ not really a coder but a pretty good bug spotter :-)
Thanks for coding this extension!

**Comment by JohnFF** [comment]
Hi Richard,

Please could you confirm for me what your settings are? Specifically, do you have only top level or only second level domain corrections set?
